swagger: '3.0.0'
info:
  title: Sub Category Model API
  description: API related to Category models
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /api/subcategory/all:
    get:
      summary: Fetch All Sub Categories
      description: Endpoint to fetch all Sub Categories
      tags:
        - Sub Category Model
      security:
        - JWT: []
      responses:
        200:
          description: Success response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Fetch all Sub Categories successfully
                  result:
                    type: array
                    items:
                      type: object
                      properties:
                        subcategoryName:
                          type: string
                          example: "Self Help"
                        categoryId:
                          type: string
                          example: "670d2fd920824883c3100257"
                        description:
                          type: string
                          example: "Self Help"
                        imageUrl:
                          type: string
                          example: "upload/subcategory/sample.jpg"
                        isActive:
                          type: boolean
                          example: true
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: An error occurred

  /api/subcategory/by-category/{categoryId}/{type}:
    get:
      summary: Fetch Sub Categories by category ID
      description: Endpoint to fetch sub categories by a given category ID
      tags:
        - Sub Category Model
      parameters:
        - name: categoryId
          in: path
          required: true
          description: The ID of the category
          schema:
            type: string
            example: "670d2fd920824883c3100257"
        - name: type
          in: path
          required: true
          description: Type of the category
          schema:
            type: string
            enum: ["kid", "parent"]
            example: "kid"
      security:
        - JWT: []
      responses:
        200:
          description: Success response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Fetch Sub Categories by category ID successfully
                  result:
                    type: array
                    items:
                      type: object
                      properties:
                        subCategoryName:
                          type: string
                          example: "Self Help"
                        categoryId:
                          type: string
                          example: "670d2fd920824883c3100257"
                        description:
                          type: string
                          example: "Self Help"
                        imageUrl:
                          type: string
                          example: "upload/category/sample.jpg"
                        isActive:
                          type: boolean
                          example: true
        404:
          description: Sub Categories not found for the given category
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: No sub categories found for this category
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: An error occurred

/api/subcategory/:
    post:
      summary: Create sub category
      description: Endpoint to Create sub category
      tags:
        - Sub Category Model
      security:
        - JWT: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                subCategoryName:
                  type: string
                  example: Stories
                categoryId:
                  type: string
                  example: "670d2fd920824883c3100257"  
                description:
                  type: string
                  example: "Desc Stories"
                imageUrl:
                  type: string
                  example: "upload/category/sample.jpg"
                isActive:
                  type: boolean
                  example: true                  
                sorting:
                  type: number
                  example: 1
                type:
                  type: string
                  enum:
                    - kid
                    - parent                            
                  example: kid
      responses:
        200:
          description: Success response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Create Data Successfully
                  result:
                    type: object
                    properties:
                      _id:
                        type: string
                        example: 670d2fd920824883c3100257
        401:
          description: Unauthorized response
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Unauthorized user

/api/subcategory/{id}:
    put:
      summary: Update sub category
      description: Endpoint to update sub category
      tags:
        - Sub Category Model
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the package
          schema:
            type: string
            example: "670d2fd920824883c3100257"      
      security:
        - JWT: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                subCategoryName:
                  type: string
                  example: Stories
                categoryId:
                  type: string
                  example: "670d2fd920824883c3100257"  
                description:
                  type: string
                  example: "Desc Stories"
                imageUrl:
                  type: string
                  example: "upload/category/sample.jpg"
                isActive:
                  type: boolean
                  example: true                  
                sorting:
                  type: number
                  example: 1
                type:
                  type: string
                  enum:
                    - kid
                    - parent                            
                  example: kid
      responses:
        200:
          description: Success response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: update Data Successfully
                  result:
                    type: object
                    properties:
                      _id:
                        type: string
                        example: 670d2fd920824883c3100257
        401:
          description: Unauthorized response
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Unauthorized user

components:
  securitySchemes:
    JWT:
      type: apiKey
      in: header
      name: Authorization
      description: JWT Bearer token
